config/routes.rb
Rails.application.routes.draw do

  get 'users/create'
  root 'homes#show'
  devise_for :users
  resource :home, only: :show
  resources :profiles do
    collection do
      get 'showresult'
    end
  end
  resources :sections
  resources :faculties
  resources :batches
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :batch
  belongs_to :faculty
  belongs_to :section
  belongs_to :user

  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    if current_user.admin?
      @users =
        User.includes(:faculties,:batches,:sections)
            .filter_by_batch_id(params[:batch_id])
            .filter_by_section_id(params[:section_id])
            .filter_by_faculty_id(params[:faculty_id])
            .order_by(params[:sort_by], params[:sort_order]).page(params[:page]).per(5)
    else
      @faculties = current_user.faculties
      @batches = current_user.batches
      @sections = current_user.sections
      @profiles = current_user.profiles
    end
  end

  def showresult
    @users = User.joins(:profiles).search
  end

  def new
    if current_user.user?
      @profile = current_user.profiles.build
    else
       redirect_to profiles_path, danger:"Admin cannot have any profiles"
    end 
  end

  def create
    @profile = current_user.profiles.build(profile_params)
    respond_to do |format|
      if @profile.save
          format.html{ redirect_to @profile, success:'Profile was successfully created' }
          format.json{render :show, status::created,location: @profile}
      else
        format.html{render :new, danger: @profile.errors.full_messages.to_sentence}
        format.json{render json: @faculty.errors, status: :unprocessable_entity}
      end
    end  
  end

  def show
    @faculties=  current_user.faculties
    @batches= current_user.batches
    @sections= current_user.sections
    if current_user.admin?
      @user = User.find(params[:id])
    end
  end

  def edit
    @profile = Profile.find(params[:id]) 
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to profiles_path, success: 'Profile is successfully updated.'
    else
      render :edit, danger: 'Profile wasnot updated'
    end  
  end

  private
  def profile_params
    params.require(:profile).permit(:faculty_id, :batch_id, :section_id,:user_id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  
  def data_sort_order(field_name)
    if params[:sort_by].blank? && field_name == 'firstname'
      'asc'
    elsif params[:sort_by]&.downcase == field_name
      params[:sort_order]
    end
  end
  
end

app/views/profiles/_admin_viewProfile.html.erb
<tbody class="profileList">
    <% @users.each do |user| %> 
        <tr data-target="<%=".profile-list-#{user.id}"%>">
            <td data-name='First Name'><%= user.firstname %></td>
            <td data-name='Middle Name'><%= user.middlename %></td>
            <td data-name='Last Name'><%= user.lastname %></td>
            <td data-name='Email'><%= user.email %></td>
            <td data-name='Permanent Address'><%= user.permanent_address %></td>
            <td data-name='Temporary Address'><%= user.temporary_address %></td>
            <td data-name='Gender'><%= user.gender %></td>
            <td data-name='Role'><%= user.role %></td>
            <td><%= link_to 'Show', profile_path(user.id), :id =>"show-button" %></td>
            <td><%= link_to 'Edit', edit_profile_path(user.id) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% class_name = "profile-list-#{user.id} profile-list" %>
        <tr style="width:40%;" class="<%= class_name %>"  >
            <th>FACULTY NAME</th>
            <th>BATCH</th>
            <th>SECTION</th>
        </tr>
        <% user.profiles.each do |profile| %>
            <tr class="<%= class_name %>" >
                <td data-name='Faculty'><%= profile.faculty.facultyname%></td>
                <td data-name='Batch'><%= profile.batch.year%></td>
                <td data-name='Section'><%= profile.section.section%></td>
                <td><%= link_to 'Show', profile_path(profile.id) %></
                td>
                <td><%= link_to 'Edit',edit_profile_path(profile.id) %></td>
                <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>    
    <% end %>   
</tbody>

app/views/profiles/_currentuser_profile.html.erb
<tbody id = "profileList">
    <tr data-toggle="modal" data-target="#myModal">
        <td><span class="glyphicon glyphicon-play"></span></td>
        <td><%= link_to current_user.firstname, profile_path(current_user.id) %></td>
        <td><%= current_user.middlename %></td>
        <td><%= current_user.lastname %></td>
        <td><%= current_user.email %></td>
        <td><%= current_user.permanent_address %></td>
        <td><%= current_user.temporary_address %></td>
        <td><%= current_user.gender %></td>
        <td><%= current_user.role %></td>
        <td><%= link_to 'Show', profile_path(current_user.id) %></td>
        <td><%= link_to 'Edit' %></td>
        <table class="table table-hover" id="profileTable" style="width: 40%;">
            <thead>
                <tr >
                    <th>FACULTY NAME</th>
                    <th>BATCH</th>
                    <th>SECTION</th>
                </tr>
            </thead>
            <tbody id = "userLists">
                <% @profiles.each do |profile| %>
                    <tr>
                        <td><%= profile.faculty.facultyname %></td>
                        <td><%= profile.batch.year %></td>
                        <td><%= profile.section.section%></td>
                        <td><%= link_to 'Show', profile_path(current_user.id) %></td>
                        <td><%= link_to 'Edit',edit_profile_path(profile.id) %></td>
                        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </tr>
</tbody>
</table>

app/views/profiles/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 class="modal-title" id="modalTitle">Modal title</h5>
      </div>
      <div class="modal-body" id="myModalBody">
        ...
      </div>
      <div class="modal-footer">
        <div class="modal-text" id="modalFooter">
        
        </div>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1 style="text-align: center;margin-top: 200px">Edit <%=current_user.firstname%>'s Profile</h1>
<div class="position-editnewForm">
    <%= form_for @profile, local: true do |form| %>
        <p>
            <label for="batch">Select batch from list:</label></br>
            <%= select("profile", "batch_id", Batch.all.collect {|b| [b.year, b.id]}, {prompt:"Select Batch"}, {class: "form-control"}) %>
        </p>
                
        <p>
            <label for="faculty">Select faculty from list:</label>
            <%= select("profile", "faculty_id", Faculty.all.collect { |b| [b.facultyname, b.id]}, {prompt:"Select faculty"}, {class: "form-control"}) %>
        </p>
        
        <p>
            <label for="section">Select section from list:</label>
            <%= select("profile", "section_id", Section.all.collect { |b| [b.section, b.id]}, {prompt:"Select section"}, {class: "form-control"}) %> 
        </p>
                
        <p>
            <div class="actions">
                <%= form.submit %>
            </div>
        </p>
    <% end %>
</div>

            

           
                

app/views/profiles/index.html.erb
<html>
    <head></head>
    <body>
        <div class="container">
            <div class="form-inline">
                <div class="position-selectForm">
                    <div class= "form-group">
                        <b>Select batch from list:</b>
                        <%= select_tag :batch_id, options_for_select(Batch.all.collect { |p| [ p.year, p.id ] }, params[:batch_id]), {prompt: 'Select Batch', class: "form-control select-form"} %>
                    </div>
                
                    <div class="form-group">
                        <b>Select Faculty from list:</b>
                        <%= select_tag("faculty_id", options_for_select(Faculty.all.collect { |p| [p.facultyname, p.id] }, params[:faculty_id]), {prompt:'Select Faculty', class: "form-control select-form"}) %>
                    </div>

                    <div class="form-group">
                        <b>Select Section From list:</b>
                        <%= select_tag("section_id", options_for_select(Section.all.collect { |p| [p.section,p.id] }, params[:section_id]), {prompt: 'Select Section', class: "form-control select-form"}) %>
                    </div>
                </div>
            </div>
            <% if current_user.user? %>
                <h1><%= current_user.firstname %> <%= current_user.middlename %> <%= current_user.lastname %>'S PROFILE</h1>
            <% end %>

            <table class="table table-hover">
                <thead>
                    <tr >
                        <th class="sort" data-sort_by="firstname" data-sort_order=<%= data_sort_order('firstname') %>> FIRSTNAME </th>
                        <th class="sort" data-sort_by="middlename" data-sort_order=<%= data_sort_order('middlename') %>>MIDDLENAME</th>
                        <th class="sort" data-sort_by="lastname" data-sort_order=<%= data_sort_order('lastname') %>>LASTNAME</th>
                        <th class="sort" data-sort_by="email" data-sort_order=<%= data_sort_order('email') %>>EMAIL</th>
                        <th class="sort" data-sort_by="permanent_address" data-sort_order=<%= data_sort_order('permanent_address') %>>Permanent Address</th>
                        <th class="sort" data-sort_by="temporary_address" data-sort_order=<%= data_sort_order('temporary_address') %>>Temporary Address</th>
                        <th>GENDER</th>
                        <th>Role</th>
                    </tr>
                </thead>
                <% if current_user.user? %>
                    <%= render 'currentuser_profile' %>
                <% end %>
                
                <% if current_user.admin? %>
                    <%= render 'admin_viewProfile' %>
                <% end %>  
            </table>  
            <% if current_user.admin? %> 
                <%= paginate @users %>
            <% end %> 
            <br>
          
            <form class="new-profile">
                <button type="submit"><%= link_to 'ADD NEW PROFILE', new_profile_path %></button>
            </form>
        </div>
    </body>
</html>

app/views/profiles/new.html.erb
<h1 style="text-align: center; margin-top: 200px;">Add <%= current_user.firstname %>'s New Profile</h1>
<div class="position-editnewForm">
  <%= form_for @profile, local: true do |form| %>
    <p>
      <label for="batch">Select batch from list:</label></br>
      <%= select("profile", "batch_id", Batch.all.collect {|b| [b.year, b.id]}, {prompt:"Select Batch"}, {class: "form-control"}) %>
    </p>

    <p>
      <label for="faculty">Select faculty from list:</label>
      <%= select("profile", "faculty_id", Faculty.all.collect { |b| [b.facultyname, b.id]}, {prompt:"Select faculty"}, {class:"form-control"}) %>
    </p>

    <p>
      <label for="section">Select section from list:</label>
      <%= select("profile", "section_id", Section.all.collect { |b| [b.section, b.id]}, {prompt:"Select section"}, {class:"form-control"}) %>      
    </p>

    <p>
      <div class="actions">
        <%= form.submit %>
      </div>
    </p>
  <% end %>
</div>

app/views/profiles/show.html.erb
<html>
  <head>
    <title>    
    </title>
  </head>
  <body>
    <% if current_user.user? %>
      <p>
        <%= image_tag current_user.image.url(:medium) %>
      </p>
      
      <p>
        <strong>STUDENT NAME:</strong>
        <%= current_user.firstname %> <%= current_user.middlename %> <%= current_user.lastname %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= current_user.email %>
      </p>
      
      <p>
        <strong>Permanent Address:</strong>
        <%= current_user.permanent_address %>
      </p>
      
      <p>
        <strong>Temporary Address:</strong>
        <%= current_user.temporary_address %>
      </p>
      
      <p>
        <strong>Facultynames:</strong>
        <%= @faculties.pluck(:facultyname).join(", ") %>
      </p>
      
      <p>
        <strong>Batches:</strong>
        <%= @batches.pluck(:year).join(", ") %>
      </p>
      
      <p>
        <strong>Sections:</strong>
        <%= @sections.pluck(:section).join(", ") %>
      </p>
      <%= link_to 'Edit', edit_profile_path(:id) %>
      <%= link_to 'Back', profiles_path %>
    <% end %>
          
    <% if current_user.admin? %>
      <p>
        <%= image_tag @user.image.url(:medium) %>
      </p>
      <p>
        <strong>STUDENT NAME:</strong>
        <%= @user.firstname %> <%= @user.middlename %> <%= @user.lastname %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <strong>Permanent Address:</strong>
        <%= @user.permanent_address %>
      </p>
      <p>
        <strong>Temporary Address:</strong>
        <%= @user.temporary_address %>
      </p>
      <p>
        <strong>Facultynames:</strong>
        <%= @user.faculties.pluck(:facultyname).join(", ") %>
      </p>
      <p>
        <strong>Batches:</strong>
        <%= @user.batches.pluck(:year).join(", ") %>
      </p>
      <p>
        <strong>Sections:</strong>
        <%= @user.sections.pluck(:section).join(", ") %>
      </p>
      <%= link_to 'Edit', edit_profile_path(:id) %>
      <%= link_to 'Back', profiles_path %>
    <% end %>
  </body>
</html>

app/views/profiles/showresult.html.erb
<html>
<head>
<script>
</script>
</head>
<body>

<div class="container">
  <div class="form-inline">
    <div class= "form-group">
      <b>Select batch from list:</b>
      <%= select("profile", "batch_id", Batch.all.collect {|p| [ p.year, p.id ] }, {prompt: 'Select Batch' }, {class: "form-control select-form"}) %>
    </div>

    <div class="form-group">
      <b>Select Faculty from list:</b>
      <%= select("profile","faculty_id", Faculty.all.collect {|p| [p.facultyname, p.id]}, {prompt:'Select Faculty'}, {class: "form-control select-form"}) %>
    </div>

    <div class="form-group">
      <b>Select Section From list:</b>
      <%= select("profile","section_id", Section.all.collect {|p| [p.section,p.id]}, {prompt: 'Select Section'},{class: "form-control select-form"}) %>
    </div>
</div>

        <% if current_user.user? %>
            <h1><%= current_user.firstname %> <%= current_user.middlename %> <%= current_user.lastname %>'S PROFILE</h1>
        <% end %>
<table class="table table-hover">
  <thead>
  <tr>
    <th class="sorting_asc" tabindex="0" aria-controls="example" rowspan="1" colspan="1" aria-label="Name: activate to sort column descending" style="width: 58px;" aria-sort="ascending" >FIRSTNAME</th>
    <th>MIDDLENAME</th>
    <th>LASTNAME</th>
    <th>EMAIL</th>
    <th>Permanent Address</th>
    <th>Temporary Address</th>
    <th>GENDER</th>
    <th>FACULTY</th>
    <th>BATCH</th>
    <th>SECTION</th>
    <th>Role</th>

    <th colspan="3"></th>
  </tr>
  </thead>
  <% if current_user.user? %>
        <tbody>
            <td><%= link_to current_user.firstname, profile_path(current_user.id) %></td>
            <td><%= current_user.middlename %></td>
            <td><%= current_user.lastname %></td>
            <td><%= current_user.email %></td>
            <td><%= current_user.permanent_address %></td>
            <td><%= current_user.temporary_address %></td>
            <td><%= current_user.gender %></td>
            <td><%= @faculties.pluck(:facultyname).join(', ') %></td>
            <td><%= @batches.pluck(:year).join(', ') %></td>
            <td><%= @sections.pluck(:section).join(', ') %></td>
            <td><%= current_user.role %></td>


            <td><%= link_to 'Show', profile_path(current_user.id) %></td>
            <td><%= link_to 'Edit', edit_profile_path(current_user.id) %></td>
            
        </tbody>
    <% end %>
    <% if current_user.admin? %>
        <% @users.each do |user| %> 
            <tbody>
                <td><%= user.firstname %></td>
                <td><%= user.middlename %></td>
                <td><%= user.lastname %></td>
                <td><%= user.email %></td>
                <td><%= user.permanent_address %></td>
                <td><%= user.temporary_address %></td>
                <td><%= user.gender %></td>
                <td><%= user.faculties.pluck(:facultyname).join(',') %></td>
                <td><%= user.batches.pluck(:year).join(',') %></td>
                <td><%= user.sections.pluck(:section).join(',') %></td> 
                <td><%= user.role %></td>
                <td><%= link_to 'Show', profile_path(user.id) %></td>
                <td><%= link_to 'Edit', edit_profile_path(user.id) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tbody>
        <% end %>    
    <% end %>  
</table>

<br>
<form>
<button type="submit"><%= link_to 'ADD NEW PROFILE', new_profile_path %></button>
</form>

<p id="hello">hello</p> 
<button id ="studentpreview">first</button>
</div>
</body>
</html>