config/routes.rb
Rails.application.routes.draw do

  get 'users/create'
  root 'homes#show'
  devise_for :users
  resource :home, only: :show
  resources :profiles do
    collection do
      get 'showresult'
    end
  end
  resources :sections
  resources :faculties
  resources :batches
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :profiles
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def new
    if current_user.admin?
      @section = Section.new
    else
      redirect_to sections_path, info: 'Users cannot create new sections.'
    end
  end

  def create
   @section = Section.new(section_args)
   respond_to do |format|
     if @section.save
       format.html {redirect_to @section, notice: 'section was successfully created'}
       format.html {render :show, status: :created, location: @section}
     else
       format.html {render :new}
       format.json { render json: @section.errors, status: :unprocessable_entity }
     end
   end
  end

  def edit
    if current_user.admin?
      @section = Section.find(params[:id])
    else
    redirect_to sections_path, info: 'User cannot update section.'  
    end
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to sections_path, info: 'Section is successfully updated.'
    else
      render :edit, danger: 'section wasnot updated'
    end
  end

  def show
    @section = Section.find(params[:id])
  end

  private
  def section_args
   params.require(:section).permit(:section)
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
  def sections
    Section.all
  end
end

app/views/sections/edit.html.erb
<h1>Edit Section</h1>
<%= form_for @section, url: sections_path, local: true do |form| %>
  <p>
    <div class="field">
      <%= form.label :section %>
      <%= form.text_field :section%>
    </div>
    </p>

    <p>
    <div class="actions">
      <%= form.submit %>
    </div>
    </p>
<% end %>

app/views/sections/index.html.erb
<div class="container">
  <h1>SECTIONS DETAILS</h1>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>SECTION NAME</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @sections.each do |section| %>
        <tr class="<%= cycle('list1','list2')%>">
          <td><%= link_to section.section %></td>

          <td><%= link_to 'Show', section_path(section.id) %></td>
          <td><%= link_to 'Edit', edit_section_path(section.id) %></td>
          <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'ADD NEW SECTION', new_section_path %>
</div>

app/views/sections/new.html.erb
<h1>Add New Section</h1>
<%= form_for @section, url: sections_path, local: true do |form| %>
  <p>
    <div class="field">
      <%= form.label :section %>
      <%= form.text_field :section%>
    </div>
    </p>

    <p>
    <div class="actions">
      <%= form.submit %>
    </div>
    </p>
<% end %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>SECTION NAME:</strong>
  <%= @section.section %>
</p>

<%= link_to 'Edit', edit_section_path(:id) %>
<%= link_to 'Back', sections_path %>