config/routes.rb
Rails.application.routes.draw do

  get 'users/create'
  root 'homes#show'
  devise_for :users
  resource :home, only: :show
  resources :profiles do
    collection do
      get 'showresult'
    end
  end
  resources :sections
  resources :faculties
  resources :batches
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :profiles
  has_many :faculties, through: :profiles
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController


  def index
    @batches= Batch.all
  end

  def new
    if current_user.admin?
      @batch= Batch.new
    else
      redirect_to batches_path, danger: 'Users cannot create new Batch.'
    end
  end

  def show
   @batch= Batch.find(params[:id])
  end

  def create
    @batch= Batch.new(batch_params)
    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, success: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    if current_user.admin?
      @batch = Batch.find(params[:id])
    else
      redirect_to batches_path, info: 'Users canot update batches.'
    end
  end

  def update
    @batch = Batch.find(params[:id])
    if @batch.update(batch_params)
    redirect_to batches_path, success: 'Batch was successfully updated.' 
    else
      render :edit, danger: 'Batch wasnot updated' 
    end
  end

  private
  def batch_params
   params.require(:batch).permit(:year)
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
  def batches
    Batch.all
  end
  
end

app/views/batches/edit.html.erb
<h1>Edit Batch</h1>
<%= form_for @batch, local: true do |form| %>
  <p>
    <div class="field">
      <%= form.label :YEAR %>
      <%= form.text_field :year%>
    </div>
    </p>


    <p>
    <div class="actions">
      <%= form.submit %>
    </div>
    </p>
<% end %>

app/views/batches/faculties.html.erb
</form>
<h1>FACULTIES DETAILS</h1>

<table>
  <thead>
  <tr>
    <th>FACULTY NAME</th>
    <th>TOTAL NUMBER OF STUDENTS</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>

  <% @faculties.each do |faculty| %>
      <tr class="<%= cycle('list1','list2')%>">
        <td><%= link_to faculty.facultyname, batch_faculty_sections_path(faculty.id) %></td>

        <td><%= link_to 'Show', faculty_path(faculty.id) %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty.id) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'ADD NEW FACULTY', new_faculty_path %>

app/views/batches/index.html.erb
<div class="container">
  <h1>BATCH DETAILS</h1>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>BATCH</th>

      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @batches.each do |batch| %>
        <tr class="<%= cycle('list1','list2')%>">
          <td><%=link_to batch.year%></td>

          <td><%= link_to 'Show', batch_path(batch.id) %></td>
          <td><%= link_to 'Edit', edit_batch_path(batch.id) %></td>
          <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'ADD NEW BATCH', new_batch_path %>
</div>

app/views/batches/new.html.erb
<h1>Add New Batch</h1>
<%= form_for @batch, local: true do |form| %>
  <p>
    <div class="field">
      <%= form.label :YEAR %>
      <%= form.text_field :year%>
    </div>
    </p>


    <p>
    <div class="actions">
      <%= form.submit %>
    </div>
    </p>
<% end %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>BATCH:</strong>
  <%= @batch.year %>
</p>

<%= link_to 'Edit', edit_batch_path %>
<%= link_to 'Back', batches_path %>