config/routes.rb
Rails.application.routes.draw do

  get 'users/create'
  root 'homes#show'
  devise_for :users
  resource :home, only: :show
  resources :profiles do
    collection do
      get 'showresult'
    end
  end
  resources :sections
  resources :faculties
  resources :batches
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <head>
    <title>LogicPort</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags%>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag("application") %>
  </head>
  <body>
    <%= render 'toastr_rails/flash' %>
    <div class="container-fluid">
      <% if user_signed_in? %>
        <div class="student-loggedin-info">
          <a class="button" id="popupProfile" > 
            <%= current_user.firstname %> <%= current_user.middlename %> <%= current_user.lastname %><%= image_tag current_user.image.url(:small) %>
          </a>
        </div>
        <div id="popup1" class="overlay">
          <div class="popup">
            <%= image_tag current_user.image.url(:medium), :class => "img-circular" %>
            <button class="close" id='popup-close-button'>&times;</button>
            <div class="content">
              <br><br> <h4><%= current_user.firstname %> <%= current_user.middlename %> 
              <%= current_user.lastname %></h4>
              <h4><%=current_user.email %></h4>
              <h4><%=current_user.student_phone %></h4>
              <hr>
              <div class="popup-base">
                <button >
                  <%= link_to 'Sign Out',destroy_user_session_path, method: 'delete' %>
                </button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <div class="hello">
        <h1 style="text-align:center;">ADVANCED COLLEGE OF ENGINEERING AND MANAGEMENT</h1>
        <nav class="navbar navbar-inverse">
          <ul class="nav navbar-nav">
            <li><span class="glyphicon glyphicon-align-justify"></span></li>
            <li class="active"><%= link_to 'Home',root_path %></li>
            <li><%= link_to 'GALLERY' %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                Faculty<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#">Page 1-1</a>
                </li>
                <li>
                  <a href="#">Page 1-2</a>
                </li>
                <li>
                  <a href="#">Page 1-3</a>
                </li>
              </ul>
            </li>
            <li><a href="#">Admission</a></li>
            <li><%= link_to 'MIS',profiles_path %></li>
          </ul>
          <ul class="sign-options">
            <% if user_signed_in? %>
              <li >
                <%= link_to 'Sign Out',destroy_user_session_path, method: 'delete' %>
              </li>
            <% end %>
            <%if !user_signed_in? %>
              <li ><%= link_to 'Sign Up', new_user_registration_path %></li >
              <li ><%= link_to 'Login',new_user_session_path %> </li>
            <% end %>
          </ul>
        </nav>
      </div>
      <%= yield %>      
    </div>
  </body>
</html>
      
                